In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dudam\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dudam\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dudam\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dudam\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dudam\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dudam\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

# Nazwa pliku Excel (może być ścieżka względna do folderu roboczego)
dane = 'dane_surowe.xlsx'

# Wczytanie całego pliku do DataFrame
df = pd.read_excel(dane, engine='openpyxl')

# Wyświetlenie pierwszych wierszy
print(df.head())
print(df)

        Kod               Nazwa  ogółem Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0       NaN                 NaN    2020       2021       2022       2023
1       NaN                 NaN  [szt.]     [szt.]     [szt.]     [szt.]
2       0.0              POLSKA   22384      21841      20476      20065
3  200000.0        DOLNOŚLĄSKIE    1490       1647       1808       1738
4  400000.0  KUJAWSKO-POMORSKIE     791        774        744        745

  Unnamed: 6 wina kierujących pojazdami - ogółem Unnamed: 8 Unnamed: 9  ...  \
0       2024                                2020       2021       2022  ...
1     [szt.]                              [szt.]     [szt.]     [szt.]  ...
2      20607                               20999      20623      19391  ...
3       1821                                1393       1542       1702  ...
4        746                                 746        727        709  ...

  wina pieszych - nieostrożne wejście na jezdnię Unnamed: 48 Unnamed: 49  \
0                                           2020        2021        2022
1                                         [szt.]      [szt.]      [szt.]
2                                            830         759         678
3                                             49          63          55
4                                             28          29          26

  Unnamed: 50 Unnamed: 51 wina pieszych - pozostałe Unnamed: 53 Unnamed: 54  \
0        2023        2024                      2020        2021        2022
1      [szt.]      [szt.]                    [szt.]      [szt.]      [szt.]
2         622         558                       555         459         407
3          46          48                        48          42          51
4          33          22                        17          18           9

  Unnamed: 55 Unnamed: 56
0        2023        2024
1      [szt.]      [szt.]
2         385         413
3          41          56
4          19          13

[5 rows x 57 columns]
          Kod                Nazwa  ogółem Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN                  NaN    2020       2021       2022       2023
1         NaN                  NaN  [szt.]     [szt.]     [szt.]     [szt.]
2         0.0               POLSKA   22384      21841      20476      20065
3    200000.0         DOLNOŚLĄSKIE    1490       1647       1808       1738
4    400000.0   KUJAWSKO-POMORSKIE     791        774        744        745
5    600000.0            LUBELSKIE     897        863        767        763
6    800000.0             LUBUSKIE     581        516        483        431
7   1000000.0              ŁÓDZKIE    2332       2208       2108       2029
8   1200000.0          MAŁOPOLSKIE    2089       2140       2136       2108
9   1400000.0          MAZOWIECKIE    2880       2988       2811       2723
10  1600000.0             OPOLSKIE     466        520        427        447
11  1800000.0         PODKARPACKIE    1114       1181       1009       1140
12  2000000.0            PODLASKIE     417        418        321        329
13  2200000.0            POMORSKIE    1748       1699       1523       1492
14  2400000.0              ŚLĄSKIE    2265       2127       1922       1818
15  2600000.0       ŚWIĘTOKRZYSKIE     772        715        591        623
16  2800000.0  WARMIŃSKO-MAZURSKIE     962        854        771        694
17  3000000.0        WIELKOPOLSKIE    2723       2317       2224       2248
18  3200000.0   ZACHODNIOPOMORSKIE     857        874        831        737

   Unnamed: 6 wina kierujących pojazdami - ogółem Unnamed: 8 Unnamed: 9  ...  \
0        2024                                2020       2021       2022  ...
1      [szt.]                              [szt.]     [szt.]     [szt.]  ...
2       20607                               20999      20623      19391  ...
3        1821                                1393       1542       1702  ...
4         746                                 746        727        709  ...
5         817                                 827        799        716  ...
6         438                                 551        497        459  ...
7        2106                                2199       2093       1997  ...
8        2382                                1957       1978       2010  ...
9        2770                                2695       2828       2664  ...
10        468                                 451        504        413  ...
11        981                                1032       1116        952  ...
12        338                                 393        400        310  ...
13       1618                                1639       1623       1461  ...
14       1712                                2087       1989       1810  ...
15        618                                 720        672        553  ...
16        709                                 912        818        725  ...
17       2380                                2596       2205       2126  ...
18        703                                 801        832        784  ...

   wina pieszych - nieostrożne wejście na jezdnię Unnamed: 48 Unnamed: 49  \
0                                            2020        2021        2022
1                                          [szt.]      [szt.]      [szt.]
2                                             830         759         678
3                                              49          63          55
4                                              28          29          26
5                                              47          37          30
6                                              22          12          15
7                                              89          74          72
8                                              72         110          77
9                                             102          86          83
10                                              8          12           7
11                                             59          46          46
12                                             16           9           5
13                                             72          51          45
14                                            116          91          74
15                                             29          27          23
16                                             33          25          32
17                                             61          58          54
18                                             27          29          34

   Unnamed: 50 Unnamed: 51 wina pieszych - pozostałe Unnamed: 53 Unnamed: 54  \
0         2023        2024                      2020        2021        2022
1       [szt.]      [szt.]                    [szt.]      [szt.]      [szt.]
2          622         558                       555         459         407
3           46          48                        48          42          51
4           33          22                        17          18           9
5           35          31                        23          27          21
6            9          11                         8           7           9
7           49          49                        44          41          39
8           85          63                        60          52          49
9           76          74                        83          74          64
10           7           8                         7           4           7
11          47          23                        23          19          11
12           6           9                         8           9           6
13          39          40                        37          25          17
14          77          57                        62          47          38
15          24          21                        23          16          15
16          12          14                        17          11          14
17          55          69                        66          54          44
18          22          19                        29          13          13

   Unnamed: 55 Unnamed: 56
0         2023        2024
1       [szt.]      [szt.]
2          385         413
3           41          56
4           19          13
5           22          16
6            3           8
7           36          44
8           45          61
9           52          68
10           4           4
11          15           9
12           9           4
13          18          24
14          37          27
15          18          10
16          10          12
17          41          41
18          15          16

[19 rows x 57 columns]

In [4]:
print(df.isnull().sum())

Kod                                                                                   2
Nazwa                                                                                 2
ogółem                                                                                0
Unnamed: 3                                                                            0
Unnamed: 4                                                                            0
Unnamed: 5                                                                            0
Unnamed: 6                                                                            0
wina kierujących pojazdami - ogółem                                                   0
Unnamed: 8                                                                            0
Unnamed: 9                                                                            0
Unnamed: 10                                                                           0
Unnamed: 11                                                                           0
wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu              0
Unnamed: 13                                                                           0
Unnamed: 14                                                                           0
Unnamed: 15                                                                           0
Unnamed: 16                                                                           0
wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu                0
Unnamed: 18                                                                           0
Unnamed: 19                                                                           0
Unnamed: 20                                                                           0
Unnamed: 21                                                                           0
wina kierujących pojazdami - nieprawidłowe wyprzedzanie                               0
Unnamed: 23                                                                           0
Unnamed: 24                                                                           0
Unnamed: 25                                                                           0
Unnamed: 26                                                                           0
wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych                  0
Unnamed: 28                                                                           0
Unnamed: 29                                                                           0
Unnamed: 30                                                                           0
Unnamed: 31                                                                           0
wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami    0
Unnamed: 33                                                                           0
Unnamed: 34                                                                           0
Unnamed: 35                                                                           0
Unnamed: 36                                                                           0
wina kierujących pojazdami - pozostałe                                                0
Unnamed: 38                                                                           0
Unnamed: 39                                                                           0
Unnamed: 40                                                                           0
Unnamed: 41                                                                           0
wina pieszych - ogółem                                                                0
Unnamed: 43                                                                           0
Unnamed: 44                                                                           0
Unnamed: 45                                                                           0
Unnamed: 46                                                                           0
wina pieszych - nieostrożne wejście na jezdnię                                        0
Unnamed: 48                                                                           0
Unnamed: 49                                                                           0
Unnamed: 50                                                                           0
Unnamed: 51                                                                           0
wina pieszych - pozostałe                                                             0
Unnamed: 53                                                                           0
Unnamed: 54                                                                           0
Unnamed: 55                                                                           0
Unnamed: 56                                                                           0
dtype: int64

In [5]:
print(df[df.isnull().any(axis=1)])

   Kod Nazwa  ogółem Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0  NaN   NaN    2020       2021       2022       2023       2024
1  NaN   NaN  [szt.]     [szt.]     [szt.]     [szt.]     [szt.]

  wina kierujących pojazdami - ogółem Unnamed: 8 Unnamed: 9  ...  \
0                                2020       2021       2022  ...
1                              [szt.]     [szt.]     [szt.]  ...

  wina pieszych - nieostrożne wejście na jezdnię Unnamed: 48 Unnamed: 49  \
0                                           2020        2021        2022
1                                         [szt.]      [szt.]      [szt.]

  Unnamed: 50 Unnamed: 51 wina pieszych - pozostałe Unnamed: 53 Unnamed: 54  \
0        2023        2024                      2020        2021        2022
1      [szt.]      [szt.]                    [szt.]      [szt.]      [szt.]

  Unnamed: 55 Unnamed: 56
0        2023        2024
1      [szt.]      [szt.]

[2 rows x 57 columns]

In [6]:
print(df.columns)

Index(['Kod', 'Nazwa', 'ogółem', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'wina kierujących pojazdami - ogółem', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'wina kierujących pojazdami - pozostałe', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'wina pieszych - ogółem', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'wina pieszych - nieostrożne wejście na jezdnię', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'wina pieszych - pozostałe', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56'],
      dtype='object')

In [7]:
import pandas as pd

df = pd.read_excel('dane_surowe.xlsx', engine='openpyxl', header=None)

# Wybierz dwa wiersze nagłówków
main_headers = df.iloc[0].fillna(method='ffill')
year_headers = df.iloc[1].fillna(method='ffill')

# Zbuduj kolumny jako: [kategoria]_[rok] (nie dodawać nan)
new_columns = []
for cat, year in zip(main_headers, year_headers):
    if pd.notna(year) and year not in ["", "nan"]:
        new_columns.append(f"{cat}_{year}")
    else:
        new_columns.append(str(cat))

df = df.iloc[2:]
df.columns = new_columns
df = df.reset_index(drop=True)

print(df.columns)

Index(['Kod', 'Nazwa', 'ogółem_2020', 'ogółem_2021', 'ogółem_2022',
       'ogółem_2023', 'ogółem_2024',
       'wina kierujących pojazdami - ogółem_2020',
       'wina kierujących pojazdami - ogółem_2021',
       'wina kierujących pojazdami - ogółem_2022',
       'wina kierujących pojazdami - ogółem_2023',
       'wina kierujących pojazdami - ogółem_2024',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2020',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2021',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2022',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2023',
       'wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2024',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2020',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2021',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2022',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2023',
       'wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2024',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2020',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2021',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2022',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2023',
       'wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2024',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2020',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2021',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2022',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2023',
       'wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2024',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2020',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2021',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2022',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2023',
       'wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2024',
       'wina kierujących pojazdami - pozostałe_2020',
       'wina kierujących pojazdami - pozostałe_2021',
       'wina kierujących pojazdami - pozostałe_2022',
       'wina kierujących pojazdami - pozostałe_2023',
       'wina kierujących pojazdami - pozostałe_2024',
       'wina pieszych - ogółem_2020', 'wina pieszych - ogółem_2021',
       'wina pieszych - ogółem_2022', 'wina pieszych - ogółem_2023',
       'wina pieszych - ogółem_2024',
       'wina pieszych - nieostrożne wejście na jezdnię_2020',
       'wina pieszych - nieostrożne wejście na jezdnię_2021',
       'wina pieszych - nieostrożne wejście na jezdnię_2022',
       'wina pieszych - nieostrożne wejście na jezdnię_2023',
       'wina pieszych - nieostrożne wejście na jezdnię_2024',
       'wina pieszych - pozostałe_2020', 'wina pieszych - pozostałe_2021',
       'wina pieszych - pozostałe_2022', 'wina pieszych - pozostałe_2023',
       'wina pieszych - pozostałe_2024'],
      dtype='object')

C:\Users\dudam\AppData\Local\Temp\ipykernel_15648\3482124764.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  main_headers = df.iloc[0].fillna(method='ffill')
C:\Users\dudam\AppData\Local\Temp\ipykernel_15648\3482124764.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  year_headers = df.iloc[1].fillna(method='ffill')

In [8]:
# 1. Usuwanie wierszy i kolumn, gdzie wszystkie dane są puste
df = df.dropna(axis=0, how='all')
df = df.dropna(axis=1, how='all')

# 2. Usuwanie duplikatów
df = df.drop_duplicates()

# 3. Usuwanie pojedynczych braków danych (np. NaN) w kolumnach istotnych
df = df.dropna()  # lub df = df.fillna(0) jeśli chcesz uzupełnić zerem

# 4. Czyszczenie nazw kolumn ze spacji
df.columns = df.columns.str.strip()

# 5. Przykład transformacji kolumny na typ liczbowy (jeśli masz takie dane)
# df['kolumna_liczba'] = pd.to_numeric(df['kolumna_liczba'], errors='coerce')

# 6. Wyświetl po czyszczeniu
print(df.head())
print(df.info())

       Kod               Nazwa ogółem_2020 ogółem_2021 ogółem_2022  \
1  0000000              POLSKA       22384       21841       20476
2  0200000        DOLNOŚLĄSKIE        1490        1647        1808
3  0400000  KUJAWSKO-POMORSKIE         791         774         744
4  0600000           LUBELSKIE         897         863         767
5  0800000            LUBUSKIE         581         516         483

  ogółem_2023 ogółem_2024 wina kierujących pojazdami - ogółem_2020  \
1       20065       20607                                    20999
2        1738        1821                                     1393
3         745         746                                      746
4         763         817                                      827
5         431         438                                      551

  wina kierujących pojazdami - ogółem_2021  \
1                                    20623
2                                     1542
3                                      727
4                                      799
5                                      497

  wina kierujących pojazdami - ogółem_2022  ...  \
1                                    19391  ...
2                                     1702  ...
3                                      709  ...
4                                      716  ...
5                                      459  ...

  wina pieszych - nieostrożne wejście na jezdnię_2020  \
1                                                830
2                                                 49
3                                                 28
4                                                 47
5                                                 22

  wina pieszych - nieostrożne wejście na jezdnię_2021  \
1                                                759
2                                                 63
3                                                 29
4                                                 37
5                                                 12

  wina pieszych - nieostrożne wejście na jezdnię_2022  \
1                                                678
2                                                 55
3                                                 26
4                                                 30
5                                                 15

  wina pieszych - nieostrożne wejście na jezdnię_2023  \
1                                                622
2                                                 46
3                                                 33
4                                                 35
5                                                  9

  wina pieszych - nieostrożne wejście na jezdnię_2024  \
1                                                558
2                                                 48
3                                                 22
4                                                 31
5                                                 11

  wina pieszych - pozostałe_2020 wina pieszych - pozostałe_2021  \
1                            555                            459
2                             48                             42
3                             17                             18
4                             23                             27
5                              8                              7

  wina pieszych - pozostałe_2022 wina pieszych - pozostałe_2023  \
1                            407                            385
2                             51                             41
3                              9                             19
4                             21                             22
5                              9                              3

  wina pieszych - pozostałe_2024
1                            413
2                             56
3                             13
4                             16
5                              8

[5 rows x 57 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 1 to 17
Data columns (total 57 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   Kod                                                                                      17 non-null     object
 1   Nazwa                                                                                    17 non-null     object
 2   ogółem_2020                                                                              17 non-null     object
 3   ogółem_2021                                                                              17 non-null     object
 4   ogółem_2022                                                                              17 non-null     object
 5   ogółem_2023                                                                              17 non-null     object
 6   ogółem_2024                                                                              17 non-null     object
 7   wina kierujących pojazdami - ogółem_2020                                                 17 non-null     object
 8   wina kierujących pojazdami - ogółem_2021                                                 17 non-null     object
 9   wina kierujących pojazdami - ogółem_2022                                                 17 non-null     object
 10  wina kierujących pojazdami - ogółem_2023                                                 17 non-null     object
 11  wina kierujących pojazdami - ogółem_2024                                                 17 non-null     object
 12  wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2020            17 non-null     object
 13  wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2021            17 non-null     object
 14  wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2022            17 non-null     object
 15  wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2023            17 non-null     object
 16  wina kierujących pojazdami - niedostosowanie prędkości do warunków ruchu_2024            17 non-null     object
 17  wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2020              17 non-null     object
 18  wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2021              17 non-null     object
 19  wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2022              17 non-null     object
 20  wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2023              17 non-null     object
 21  wina kierujących pojazdami - nieprzestrzeganie pierwszeństwa przejazdu_2024              17 non-null     object
 22  wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2020                             17 non-null     object
 23  wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2021                             17 non-null     object
 24  wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2022                             17 non-null     object
 25  wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2023                             17 non-null     object
 26  wina kierujących pojazdami - nieprawidłowe wyprzedzanie_2024                             17 non-null     object
 27  wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2020                17 non-null     object
 28  wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2021                17 non-null     object
 29  wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2022                17 non-null     object
 30  wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2023                17 non-null     object
 31  wina kierujących pojazdami - nieprawidłowe zachowanie wobec pieszych_2024                17 non-null     object
 32  wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2020  17 non-null     object
 33  wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2021  17 non-null     object
 34  wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2022  17 non-null     object
 35  wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2023  17 non-null     object
 36  wina kierujących pojazdami - niezachowanie bezpiecznej odległości między pojazdami_2024  17 non-null     object
 37  wina kierujących pojazdami - pozostałe_2020                                              17 non-null     object
 38  wina kierujących pojazdami - pozostałe_2021                                              17 non-null     object
 39  wina kierujących pojazdami - pozostałe_2022                                              17 non-null     object
 40  wina kierujących pojazdami - pozostałe_2023                                              17 non-null     object
 41  wina kierujących pojazdami - pozostałe_2024                                              17 non-null     object
 42  wina pieszych - ogółem_2020                                                              17 non-null     object
 43  wina pieszych - ogółem_2021                                                              17 non-null     object
 44  wina pieszych - ogółem_2022                                                              17 non-null     object
 45  wina pieszych - ogółem_2023                                                              17 non-null     object
 46  wina pieszych - ogółem_2024                                                              17 non-null     object
 47  wina pieszych - nieostrożne wejście na jezdnię_2020                                      17 non-null     object
 48  wina pieszych - nieostrożne wejście na jezdnię_2021                                      17 non-null     object
 49  wina pieszych - nieostrożne wejście na jezdnię_2022                                      17 non-null     object
 50  wina pieszych - nieostrożne wejście na jezdnię_2023                                      17 non-null     object
 51  wina pieszych - nieostrożne wejście na jezdnię_2024                                      17 non-null     object
 52  wina pieszych - pozostałe_2020                                                           17 non-null     object
 53  wina pieszych - pozostałe_2021                                                           17 non-null     object
 54  wina pieszych - pozostałe_2022                                                           17 non-null     object
 55  wina pieszych - pozostałe_2023                                                           17 non-null     object
 56  wina pieszych - pozostałe_2024                                                           17 non-null     object
dtypes: object(57)
memory usage: 7.7+ KB
None

In [9]:
print(df.isnull().sum().sum()) 
print(df.isnull().any().any())   # True/False, czy są jakiekolwiek NaN w całej ramce

0
False

In [10]:
# Zapisuje dane do pliku 
df.to_excel('dane.xlsx', index=False)

In [11]:
import pandas as pd

# Wczytujemy wyczyszczony plik do zmiennej DANE
dane = pd.read_excel('dane.xlsx')

# Wyświetlamy podgląd w notatniku
dane

,Kod,Nazwa,ogółem_2020,ogółem_2021,ogółem_2022,ogółem_2023,ogółem_2024,wina kierujących pojazdami - ogółem_2020,wina kierujących pojazdami - ogółem_2021,wina kierujących pojazdami - ogółem_2022,...,wina pieszych - nieostrożne wejście na jezdnię_2020,wina pieszych - nieostrożne wejście na jezdnię_2021,wina pieszych - nieostrożne wejście na jezdnię_2022,wina pieszych - nieostrożne wejście na jezdnię_2023,wina pieszych - nieostrożne wejście na jezdnię_2024,wina pieszych - pozostałe_2020,wina pieszych - pozostałe_2021,wina pieszych - pozostałe_2022,wina pieszych - pozostałe_2023,wina pieszych - pozostałe_2024
0,0,POLSKA,22384,21841,20476,20065,20607,20999,20623,19391,...,830,759,678,622,558,555,459,407,385,413
1,200000,DOLNOŚLĄSKIE,1490,1647,1808,1738,1821,1393,1542,1702,...,49,63,55,46,48,48,42,51,41,56
2,400000,KUJAWSKO-POMORSKIE,791,774,744,745,746,746,727,709,...,28,29,26,33,22,17,18,9,19,13
3,600000,LUBELSKIE,897,863,767,763,817,827,799,716,...,47,37,30,35,31,23,27,21,22,16
4,800000,LUBUSKIE,581,516,483,431,438,551,497,459,...,22,12,15,9,11,8,7,9,3,8
5,1000000,ŁÓDZKIE,2332,2208,2108,2029,2106,2199,2093,1997,...,89,74,72,49,49,44,41,39,36,44
6,1200000,MAŁOPOLSKIE,2089,2140,2136,2108,2382,1957,1978,2010,...,72,110,77,85,63,60,52,49,45,61
7,1400000,MAZOWIECKIE,2880,2988,2811,2723,2770,2695,2828,2664,...,102,86,83,76,74,83,74,64,52,68
8,1600000,OPOLSKIE,466,520,427,447,468,451,504,413,...,8,12,7,7,8,7,4,7,4,4
9,1800000,PODKARPACKIE,1114,1181,1009,1140,981,1032,1116,952,...,59,46,46,47,23,23,19,11,15,9
10,2000000,PODLASKIE,417,418,321,329,338,393,400,310,...,16,9,5,6,9,8,9,6,9,4
11,2200000,POMORSKIE,1748,1699,1523,1492,1618,1639,1623,1461,...,72,51,45,39,40,37,25,17,18,24
12,2400000,ŚLĄSKIE,2265,2127,1922,1818,1712,2087,1989,1810,...,116,91,74,77,57,62,47,38,37,27
13,2600000,ŚWIĘTOKRZYSKIE,772,715,591,623,618,720,672,553,...,29,27,23,24,21,23,16,15,18,10
14,2800000,WARMIŃSKO-MAZURSKIE,962,854,771,694,709,912,818,725,...,33,25,32,12,14,17,11,14,10,12
15,3000000,WIELKOPOLSKIE,2723,2317,2224,2248,2380,2596,2205,2126,...,61,58,54,55,69,66,54,44,41,41
16,3200000,ZACHODNIOPOMORSKIE,857,874,831,737,703,801,832,784,...,27,29,34,22,19,29,13,13,15,16

In [12]:

# Wczytujemy wyczyszczony plik do zmiennej DANE
dane_surowe = pd.read_excel('dane_surowe.xlsx')

# Wyświetlamy podgląd w notatniku
dane_surowe

,Kod,Nazwa,ogółem,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,wina kierujących pojazdami - ogółem,Unnamed: 8,Unnamed: 9,...,wina pieszych - nieostrożne wejście na jezdnię,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,wina pieszych - pozostałe,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56
0,NaN,NaN,2020,2021,2022,2023,2024,2020,2021,2022,...,2020,2021,2022,2023,2024,2020,2021,2022,2023,2024
1,NaN,NaN,[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],...,[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.],[szt.]
2,0.0,POLSKA,22384,21841,20476,20065,20607,20999,20623,19391,...,830,759,678,622,558,555,459,407,385,413
3,200000.0,DOLNOŚLĄSKIE,1490,1647,1808,1738,1821,1393,1542,1702,...,49,63,55,46,48,48,42,51,41,56
4,400000.0,KUJAWSKO-POMORSKIE,791,774,744,745,746,746,727,709,...,28,29,26,33,22,17,18,9,19,13
5,600000.0,LUBELSKIE,897,863,767,763,817,827,799,716,...,47,37,30,35,31,23,27,21,22,16
6,800000.0,LUBUSKIE,581,516,483,431,438,551,497,459,...,22,12,15,9,11,8,7,9,3,8
7,1000000.0,ŁÓDZKIE,2332,2208,2108,2029,2106,2199,2093,1997,...,89,74,72,49,49,44,41,39,36,44
8,1200000.0,MAŁOPOLSKIE,2089,2140,2136,2108,2382,1957,1978,2010,...,72,110,77,85,63,60,52,49,45,61
9,1400000.0,MAZOWIECKIE,2880,2988,2811,2723,2770,2695,2828,2664,...,102,86,83,76,74,83,74,64,52,68
10,1600000.0,OPOLSKIE,466,520,427,447,468,451,504,413,...,8,12,7,7,8,7,4,7,4,4
11,1800000.0,PODKARPACKIE,1114,1181,1009,1140,981,1032,1116,952,...,59,46,46,47,23,23,19,11,15,9
12,2000000.0,PODLASKIE,417,418,321,329,338,393,400,310,...,16,9,5,6,9,8,9,6,9,4
13,2200000.0,POMORSKIE,1748,1699,1523,1492,1618,1639,1623,1461,...,72,51,45,39,40,37,25,17,18,24
14,2400000.0,ŚLĄSKIE,2265,2127,1922,1818,1712,2087,1989,1810,...,116,91,74,77,57,62,47,38,37,27
15,2600000.0,ŚWIĘTOKRZYSKIE,772,715,591,623,618,720,672,553,...,29,27,23,24,21,23,16,15,18,10
16,2800000.0,WARMIŃSKO-MAZURSKIE,962,854,771,694,709,912,818,725,...,33,25,32,12,14,17,11,14,10,12
17,3000000.0,WIELKOPOLSKIE,2723,2317,2224,2248,2380,2596,2205,2126,...,61,58,54,55,69,66,54,44,41,41
18,3200000.0,ZACHODNIOPOMORSKIE,857,874,831,737,703,801,832,784,...,27,29,34,22,19,29,13,13,15,16